### ISSUE TITLE
W&B config synced only at the end of the run

### ISSUE THREAD

**Issue by CedricLeon** [klieret/wandb-offline-sync-hook#100]
Hi!
This is a question more than an issue

## Problem
I am running quite long sweeps offline and I realized that the config of W&B is uploaded only at the end of the run (when `mode="offline"`). Or worse, if the run "crashes", because of the job time-limit or some other event, the config is never uploaded. Which makes the run pretty useless.

## Context
I have seen the issue you opened [#6974](https://github.com/wandb/wandb/issues/6974) as well as this feature recommendation [#6952](https://github.com/wandb/wandb/issues/6952), but I don't see a clean solution (IMO, using Artifacts or Text files completely defeats the purpose).

## Setup
I tried forcing the `wandb.config` at the beginning of the run (instead of waiting for the `Lightning.Trainer` to initialize it), but it did not seem to change anything. The problem seems to come from the synchronization.
Here is how I do it (using an hydra config):
```python
wandb.config = OmegaConf.to_container(cfg, resolve=True, throw_on_missing=True)
wandb.init(entity=cfg.entity, project=cfg.project, ...)
```
Do you have a current work around? Or a glimpse of a solution?

Also, thanks for your amazing work, this is a super handy package and by far the simplest solution I have found 😁

**Comment by klieret** [comment]
Thanks for the issue @CedricLeon and for the link to https://github.com/wandb/wandb/issues/6952 (I hadn't seen that). Unfortunately I don't have any solution for this at the moment. 

It is really frustrating to be honest, especially if runs fail/get killed by a scheduler (in that case, no config is ever uploaded). 

One thing I've tried was to set the `config` via the `wandb` API during the run (with [this script](https://github.com/gnn-tracking/hyperparameter_optimization2/blob/main/bin/fix-metadata.py) that takes the hyperparameters from the lightning config and then sends them to wandb), but it seems like they get overwritten with the next sync.

**Comment by klieret** [comment]
Obviously, this is more of a bug in `wandb`, though `wandb-osh` could include a fix/workaround if only we had one (but I don't know of any). Let me know if you discover something!
