### ISSUE TITLE
Change logging level

### ISSUE THREAD

**Issue by RitwikGupta** [klieret/wandb-offline-sync-hook#73]
First of all, thank you for writing this library. This has saved us a ton of pain with compute nodes that have no internet connectivity.

Is there any way by which we can disable or lower the amount of logging? Particularly, our Slurm stderr files are filled with this on every other line:
```
12:03:11 WARNING: Syncing not active or too slow: Command /p/home/ritwik/.wandb_osh_command_dir/27111f.command file still exists
WARNING:wandb_osh:Syncing not active or too slow: Command /p/home/ritwik/.wandb_osh_command_dir/27111f.command file still exists
12:03:11 DEBUG: Wrote command file /p/home/ritwik/.wandb_osh_command_dir/27111f.command
DEBUG:wandb_osh:Wrote command file /p/home/ritwik/.wandb_osh_command_dir/27111f.command
```

It would be great if we could turn this off.

**Comment by klieret** [comment]
The new version will make this a little bit easier (see Q & A in readme). Let me know if this works for you ;)

**Comment by klieret** [comment]
Hi @RitwikGupta Sorry, missed your comment: You mean whether you can control the log messages that are shown on the compute node with the synchronization script on the head node? That's not currently possible, unfortunately.
