### ISSUE TITLE
Resuming while offline

### ISSUE THREAD

**Issue by MoH-assan** [klieret/wandb-offline-sync-hook#80]
Any way around this issue?
https://github.com/wandb/wandb/issues/4624

**Comment by klieret** [comment]
Hmm, I don't think we can do anything simple from the viewpoint of this package. If I understand correctly, `wandb` cannot resume offline runs, so this is a clear limitation from the viewpoint of the `wandb` command line client (which we use "as-is" in this package). There could be some option to read the history from the offline run, and then have whatever ML framework you're using "fake" that history and give it to wandb. But this would be quite inelegant is really out of the scope for this package.

I think the best option is to make sure the wandb issue doesn't get forgotten (I'm surprised they still didn't implement this!)
