### ISSUE TITLE
Timeout option from the CL is ignored

### ISSUE THREAD

**Issue by MoH-assan** [klieret/wandb-offline-sync-hook#82]
Hi, 
I am wondering is `wandb-osh --timeout -1` working? 

and when I try to set it to negative or extremely large positive value it make no difference. 
I still get time out warning. 

Update: 
https://github.com/klieret/wandb-offline-sync-hook/blob/4f228ece6b70d27b36f67f20f9d7a7b1f68c3093/src/wandb_osh/cli.py#L47
I guess the call to `WandbSyncer` is missing the time `timeout` thus the default is used (aka 120 sec)

Thanks

**Comment by klieret** [comment]
Very good catch, I'll fix that!

Sorry for the late reply!

**Comment by klieret** [comment]
@all-contributors please add @MoH-assan for bug
